name: vipv-server

x-db-env: &x-db-env
  POSTGRES_DB: vipv_db
  POSTGRES_USER: vipv_db_user
  POSTGRES_PASSWORD: vipv_db_password
  # POSTGRES_HOST is ignored in the db service, but used in the web service
  # to form the connection string. Matches the service name of the db service.
  POSTGRES_HOST: db

x-web-env: &x-web-env
  SECRET_KEY: "my_precious_secret_key"
  JWT_SECRET_KEY: "my_precious_overshared_key"
  # The following environment variables are used to control the client build number.
  # They are used to determine if the client is compatible with the server
  # and prompt the user to update if necessary.
  # Set to 0 to disable the check.
  CLIENT_BUILD_NUMBER_MINIMAL: ""  # client with less than this build number will be required to update
  CLIENT_BUILD_NUMBER_DEPRECATED: ""  # client with less than or equal to this build number will be recommended to update

services:
  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    environment:
      <<: [*x-db-env, *x-web-env]
    volumes:
      # This line mounts a directory from your host machine (/home/vipv-user/sessions) to a directory inside the container (/vipv-server/instance/sessions).
      # This is useful for persisting data or sharing files between the host and the container.
      # The expected files you will be able to find here are the session files uploaded by the users with the log of the beacons.
      - /home/vipv-user/sessions:/vipv-server/instance/sessions
    healthcheck:
      test: ["CMD-SHELL", "wget --output-document=- --tries=5 --timeout=1 http://localhost:5000/api/v1/up"]
      interval: 30s
      timeout: 5s
      start_period: 15s
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    environment:
      <<: *x-db-env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -t 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      # Do not change the path; see PGDATA at https://hub.docker.com/_/postgres
      - db:/var/lib/postgresql/data

volumes:
  db:
